# Generated by Django 4.0.3 on 2022-07-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='group',
            field=models.ManyToManyField(null=True, to='auth.group'),
        ),
    ]
