# Generated by Django 4.0.3 on 2022-07-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='group',
        ),
    ]
