# Generated by Django 4.0.3 on 2022-07-26 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('source', models.CharField(max_length=20)),
                ('stage', models.CharField(default='New', max_length=20)),
                ('status', models.CharField(max_length=20, null=True)),
                ('pincode', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lead_communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('Date_created', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now_add=True)),
                ('Type', models.CharField(max_length=50)),
                ('proablity', models.IntegerField(default=0)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='lead_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(choices=[('1', 'Demo'), ('2', 'Instalation')], default='1', max_length=20)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField()),
                ('demo_status', models.CharField(max_length=10)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('conversation_date', models.DateField()),
                ('renewal_date', models.DateField()),
                ('start_date', models.DateField()),
                ('subscription_used_date', models.DateField(max_length=10)),
                ('payment_cycle', models.CharField(max_length=10)),
                ('gst_no', models.CharField(max_length=50)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
