# Generated by Django 4.0.3 on 2022-07-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_communication',
            name='Type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lead_communication',
            name='proablity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
