# Generated by Django 4.0.3 on 2022-08-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_catagory_alter_lead_activity_activity_name_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.product'),
        ),
    ]
