# Generated by Django 4.0.3 on 2022-09-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_file_name', models.CharField(max_length=30)),
                ('Quanytity', models.CharField(max_length=30)),
                ('price_offered', models.CharField(max_length=30)),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.product')),
            ],
        ),
    ]
