# Generated by Django 4.0.3 on 2022-09-13 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_activity',
            name='Date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
