# Generated by Django 4.0.3 on 2022-09-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_activity_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='Quanytity',
            new_name='Quantity',
        ),
        migrations.AlterField(
            model_name='lead_activity',
            name='demo_status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Still in Progress'), ('3', 'Completed')], default='1', max_length=10),
        ),
    ]
